### ISSUE TITLE
Arduino-compatible version?

### ISSUE THREAD

**Issue by skorokithakis** [DaleGia/ESPFlash#2]
Do you think it would be possible to write an Arduino-compatible backend while leaving the interface the same? I'm using a Nano and your library has a very convenient API.

**Comment by DaleGia** [comment]
When you say arduino compatible version, do you mean a version that uses the EEPROM library to write to flash?

If so then yes, it should be possible. However all of the file system related functionality would have to go and be replaced with something else to address the element array addressing. It is also likely that maximum element array size would have to be defined at instantiation. Quite a bit less user friendly, but thats the nature when working with such small amounts of memory.

I would be happy to give it a go if/when I can get a hand on a Nano. Otherwise if you want to give it a crack, I would also be happy to give any assistance I can.

**Comment by skorokithakis** [comment]
> When you say arduino compatible version, do you mean a version that uses the EEPROM library to write to flash?

Yes, exactly. I just wrote something simple to write to the EEPROM, and handling struct versioning/initialization/etc is a bit of a hassle, and ESPFlash came to mind.

You're right that it would be less user-friendly, it might not be worth it. I would be happy to help but my C++ skills aren't great, and I would struggle with it.

It's just a thought to consider, though, nothing really pressing.
